# relative to app/config/routing.yml

# security routes

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#captcha routes

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

# fos js routes

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#_redirect_to_index:
#    path:   /
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: about
#        permanent: true

#_redirect_to_admin:
#    path:   /
#    defaults:  
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    ':home:about.html.twig'

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix: /

