parameters:
   
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_name:     symfony
    database_user:     root
    database_password: 

    mailer_transport:   smtp
    mailer_host:        127.0.0.1
    mailer_user:        service@symfony.com
    mailer_password:    service

    locale:             es

    # App Options
    
    webapp_host: 127.0.0.1:8000
    webapp_url:  http://%webapp_host%     #http://%webapp_host%   # http://%webapp_host%/symfony/web or http://127.0.0.1/symfony/web

    # Sonata Media options
    
    sonata_media.cdn.host:     %webapp_url%/uploads/media # http://127.0.0.1:8000/uploads/media

    # lexik jwt
    jwt_token_ttl: 86400