# Nelmio Api Docs

NelmioApiDocBundle:
    resource:     "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /_doc

# Lexik JWT Auth

api_login_check:
    path: /_login_check
    options:
        expose: true

# Gesdinet Jwt Refresh Token:
    
api_token_refresh:
    path:     /_token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    options:
        expose: true

# API routes

app_api:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation
    prefix:   /
