#
# more information can be found here https://sonata-project.org/bundles/page
#
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataPageBundle: ~
                    ApplicationSonataPageBundle: ~

cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_block:
    context_manager: sonata.page.block.context_manager

sonata_page:
    class:
        site:     Application\Sonata\PageBundle\Entity\Page\Site
        snapshot: Application\Sonata\PageBundle\Entity\Page\Snapshot
        page:     Application\Sonata\PageBundle\Entity\Page\Page
        block:    Application\Sonata\PageBundle\Entity\Page\Block

    slugify_service:   sonata.core.slugify.cocur # old BC value is sonata.core.slugify.native
    multisite:       host_by_locale     #host #host_by_locale # host_with_path #host_with_path_by_locale
    is_inline_edition_on:  false
    # Generates a snapshot when a page is saved (from the admin)
    direct_publication: %kernel.debug% # or %kernel.debug% if you want to publish in dev mode (but not in prod)
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response

    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^(.*)api_(.*)   # ignore api route, ie route containing 'api'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
        
        - sonata_user_security_login
        - sonata_user_security_check
        - sonata_user_security_logout
        - sonata_user_resetting_request
        - sonata_user_resetting_send_email
        - sonata_user_resetting_check_email
        - sonata_user_resetting_reset 
        - sonata_user_profile_show
        - sonata_user_profile_edit
        - sonata_user_profile_edit_authentication
        - sonata_user_change_password
        - sonata_user_registration_register
        - sonata_user_registration_check_email
        - sonata_user_registration_confirm
        - sonata_user_registration_confirmed
        - gregwar_captcha.generate_captcha
        - sonata_page_ajax_block
        - fos_js_routing_js


    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'
        #- ^/home/(.*)
        - ^/app/api/(.*)
        - ^/api/(.*)
      
    page_defaults:
    page_defaults:
        #homepage: { decorate: false, enabled: true }
        #homepage: {decorate: false} # disable decoration for homepage, key - is a page route
        #homepage: {decorate: true} # enable decoration for homepage, key - is a page route
        
    assets:
        stylesheets:
        #    - assetic/sonata_front_css.css
            - assets/themes/startbootstrap-modern-business/css/bootstrap.min.css
            - assets/themes/startbootstrap-modern-business/css/landing-page.css
            - assets/themes/startbootstrap-modern-business/font-awesome/css/font-awesome.min.css
            #- bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/applicationsonataadmin/vendor/iCheck/skins/flat/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - assets/vendor/bootstrap3-wysihtml5/src/bootstrap-wysihtml5.css
            - assets/vendor/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css
            #- assetic/sonata_front_css.css
            #- http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css

        javascripts:
        #    - assetic/sonata_front_js.js
            - assets/themes/startbootstrap-modern-business/js/jquery.js
            - assets/themes/startbootstrap-modern-business/js/bootstrap.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - assets/vendor/hinclude/hinclude.js
            - assets/vendor/bootstrap3-wysihtml5/lib/js/wysihtml5-0.3.0.js
            - assets/vendor/bootstrap3-wysihtml5/src/bootstrap3-wysihtml5.js
            - assets/vendor/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js
            #- bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            #- bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
            #- bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            #- bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            #- bundles/sonatapage/sonata-page.front.min.js  

    caches:
        esi:
            token:    add an unique token here # default is a random value
            version:  3                        # version 3 is the default on debian wheezy ...
            servers:
                # you need to ajust this configuration to match your varnish configuration
                - %sonata_page.varnish.command%
        ssi:
            token:    add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "Application\Sonata\PageBundle\Entity\Page\Block": getId


    default_template: default
    templates:
        default:
            path: 'ApplicationSonataPageBundle::default_layout.html.twig'
            name: 'Default Template'
            containers:
                 header:
                     name: Header
                     #blocks:
                     #   - sonata.block.service.text
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     HHHHHHHH
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                     FFFFFFFF

                 mapping:
                     H: header
                     T: content_top
                     C: content
                     B: content_bottom
                     F: footer

        2columns:
            path: 'ApplicationSonataPageBundle::2columns_layout.html.twig'
            name: 'Template with 2 columns'
            containers:
                 header:
                     name: Header
                 content_top:
                     name: Top content
                 left_col:
                     name: Left content
                 rigth_col:
                     name: Right content
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     HHHHHHHH
                     TTTTTTTT
                     LLLLRRRR
                     BBBBBBBB
                     FFFFFFFF

                 mapping:
                     H: header
                     T: content_top
                     L: left_col
                     R: rigth_col
                     B: content_bottom
                     F: footer

sonata_admin:
    assets:
        stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css
        javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
