# Lexik JWT Auth
lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

gesdinet_jwt_refresh_token:
    ttl: 86400
    #ttl: 2592000
    ttl_update: true    
    #firewall: api
    #user_provider: fos_user.user_provider.username_email